### ISSUE TITLE
"itemKey" causes App Store Reject

### ISSUE THREAD

**Issue by yoheiniimi** [ludei/atomic-plugins-ads#8]
Apple says,

> Your app uses or references the following non-public APIs:
> 
> itemKey
> 
> The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.
> 
> Next Steps
> 
> Please revise your app to remove any non-public APIs. If you have defined methods in your source code with the same names as the above-mentioned APIs, we suggest altering your method names so that they no longer collide with Apple's private APIs to avoid your application being flagged in future submissions.

For a example, it' in the [LDAdServiceChartboost.h](https://github.com/ludei/atomic-plugins-ads/blob/master/src/atomic/ios/chartboost/LDAdServiceChartboost.h).

> @property (nonatomic, strong) NSString *itemKey;

One thing is strange that I use this API in my oldest version APPs, but threre're no rejects with this issue.
I told Apple wondering why.

Apple replies,

> We have begun asking that all developers update their apps to remove private API’s.
> We appreciate your cooperation with these matters.

**Comment by BlueSialia** [comment]
Follow this issue in the forum https://forums.cocoon.io/t/app-store-reject-non-public-apis-itemkey/3769

**Comment by BlueSialia** [comment]
@65bc111c2a34405688ab6843758ca4a2292a34f6 Should fix this.
